language: python
sudo: false
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy
  - pypy3
install:
  - if [[ $TRAVIS_PYTHON_VERSION < 3.5 ]]; then pip install flake8 pep8-naming;else pip install flake8 pep8-naming flake8-bugbear; fi
  - flake8 --version
script:
  - ./tests.sh
